apiversion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-actions-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-actions-service
  template:
    metadata:
      labels:
        app: kubernetes-actions-service
    spec:
      containers:
        - name: kubernetes-actions-service
      image: ${{ secrets.DOCKER_USERNAME}}/&{{ secrets.DOCKER_REPOSITORY }}:latest
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-actions-service
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-actions-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
